[versions]
grpc = "1.69.0"
protobuf = "4.29.3"
jackson = "2.18.2"
log4j = "2.24.3"
junit = "5.11.4"
assertj = "3.27.3"
kafka = "3.9.0"
protobufPlugin = "0.9.5"
mcp = "2.0.1"
jetty = "12.0.21"
awssdk = "2.31.78"

[libraries]
grpc-netty-shaded = { module = "io.grpc:grpc-netty-shaded", version.ref = "grpc" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
grpc-services = { module = "io.grpc:grpc-services", version.ref = "grpc" }
grpc-inprocess = { module = "io.grpc:grpc-inprocess", version.ref = "grpc" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
tomcat-annotations = { module = "org.apache.tomcat:annotations-api", version = "6.0.53" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-dataformat-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
kafka-clients = { module = "org.apache.kafka:kafka-clients", version.ref = "kafka" }
kafka-connect-api = { module = "org.apache.kafka:connect-api", version.ref = "kafka" }
mcp-core = { module = "io.modelcontextprotocol.sdk:mcp-core", version.ref = "mcp" }
mcp-json-jackson2 = { module = "io.modelcontextprotocol.sdk:mcp-json-jackson2", version.ref = "mcp" }
jetty-server = { module = "org.eclipse.jetty:jetty-server", version.ref = "jetty" }
jetty-ee10-servlet = { module = "org.eclipse.jetty.ee10:jetty-ee10-servlet", version.ref = "jetty" }
slf4j-jdk14 = { module = "org.slf4j:slf4j-jdk14", version = "2.0.16" }
protobuf-java-util = { module = "com.google.protobuf:protobuf-java-util", version.ref = "protobuf" }
awssdk-s3 = { module = "software.amazon.awssdk:s3", version.ref = "awssdk" }

[plugins]
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
